const https = require('https');

async function createDraftPost(siteName, hostname, user, pass) {
    return new Promise((resolve) => {
        console.log(`[${siteName}] Connecting to ${hostname} as ${user}...`);
        const auth = Buffer.from(`${user}:${pass}`).toString('base64');

        const postData = JSON.stringify({
            title: `OpenClaw Connectivity Test - ${siteName}`,
            content: `This is an automated test post generated by the OpenClaw agent system to verify WordPress REST API connectivity on ${new Date().toISOString()}.`,
            status: 'draft',
            type: 'post'
        });

        const options = {
            hostname: hostname,
            path: '/wp-json/wp/v2/posts',
            method: 'POST',
            headers: {
                'Authorization': 'Basic ' + auth,
                'Content-Type': 'application/json',
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'Content-Length': Buffer.byteLength(postData)
            }
        };

        const req = https.request(options, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                if (res.statusCode === 201) {
                    const json = JSON.parse(data);
                    console.log(`✅ [${siteName}] SUCCESS! Draft post created. Post ID: ${json.id}`);
                } else {
                    console.log(`❌ [${siteName}] FAILED! Status: ${res.statusCode}`);
                    console.log(`   Response: ${data}`);
                }
                resolve();
            });
        });

        req.on('error', error => {
            console.error(`❌ [${siteName}] Network Error:`, error.message);
            resolve();
        });

        req.write(postData);
        req.end();
    });
}

async function runTests() {
    console.log("Starting WordPress Post Creation Tests...\n");

    // 1. Test Wimper (Using the confirmed Masterchef password)
    await createDraftPost(
        'Wimper',
        'n13jwn1zon.wpdns.site',
        'iro-wp',
        'SOst 4Vk3 rLge IW3V Rv5k Qe74'
    );

    // 2. Test Kidazzle (Using user provided wimperone password)
    await createDraftPost(
        'Kidazzle',
        'wdi1ba00h7.wpdns.site',
        'wimperone',
        'WGLF dfZP 5iCF A2PX qGU2 flxI'
    );

    console.log("\nTests completed.");
}

runTests();
